// src/components/orchestrator/BacklogIncubator.tsx
'use client';

import { useState, useMemo } from 'react';
import { useDraggable } from '@dnd-kit/core';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Inbox, Lightbulb, Plus, Search, Grid2x2, List as ListIcon,
  Pencil, Trash2, Play, ArrowUpRight,
} from 'lucide-react';
import { useAppStore } from '@/lib/store';
import { TaskFormDialog } from './TaskFormDialog';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { Checkbox } from '@/components/ui/checkbox';
import { cn } from '@/lib/utils';
import {
  CATEGORY_COLORS, EISENHOWER_LABELS, type Task, type EisenhowerCategory,
} from '@/lib/types';
import { formatDuration } from '@/lib/time-utils';

/* ── Shared compact table row (used by list & matrix views) ── */
function TaskRow({ task, onEdit }: { task: Task; onEdit: (t: Task) => void }) {
  const completeTask = useAppStore((s) => s.completeTask);
  const deleteTask = useAppStore((s) => s.deleteTask);
  const updateTask = useAppStore((s) => s.updateTask);
  const startTimer = useAppStore((s) => s.startTimer);

  const catColor = CATEGORY_COLORS[task.category] ?? CATEGORY_COLORS.Admin;
  const eisen = EISENHOWER_LABELS[task.eisenhowerCategory];

  return (
    <tr className="group border-b border-border/50 last:border-0 hover:bg-muted/30 transition-colors">
      <td className="px-1.5 py-1.5 w-6">
        <Checkbox
          checked={task.status === 'completed'}
          onCheckedChange={(v) => v && void completeTask(task.id)}
          className="size-3.5"
          aria-label={`Complete ${task.title}`}
        />
      </td>
      <td className="px-1.5 py-1.5 min-w-0">
        <span className={cn(
          'block text-xs font-medium truncate max-w-[200px] sm:max-w-[320px]',
          task.status === 'completed' && 'line-through text-muted-foreground',
        )}>
          {task.title}
        </span>
      </td>
      <td className="px-1.5 py-1.5 text-[10px] whitespace-nowrap">
        <span className={cn('inline-block rounded px-1 py-px font-medium', catColor)}>{task.category}</span>
      </td>
      <td className="px-1.5 py-1.5 text-[10px] text-muted-foreground tabular-nums whitespace-nowrap">
        {formatDuration(task.estimatedMinutes)}
      </td>
      <td className="px-1.5 py-1.5 text-[10px] whitespace-nowrap">
        <span className="inline-block rounded border border-border/60 px-1 py-px text-muted-foreground" title={eisen.label}>
          {eisen.short}
        </span>
      </td>
      <td className="px-1.5 py-1.5">
        <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity md:opacity-100">
          {task.status !== 'completed' && (
            <Button size="icon" variant="ghost" className="size-5" onClick={() => void startTimer(task.id, 'pomodoro')} aria-label="Start timer">
              <Play className="size-2.5" />
            </Button>
          )}
          <Button size="icon" variant="ghost" className="size-5" onClick={() => onEdit(task)} aria-label="Edit">
            <Pencil className="size-2.5" />
          </Button>
          {task.status !== 'today' && task.status !== 'completed' && (
            <Button size="icon" variant="ghost" className="size-5" onClick={() => void updateTask(task.id, { status: 'today' })} title="Today" aria-label="Move to today">
              <ArrowUpRight className="size-2.5" />
            </Button>
          )}
          <Button size="icon" variant="ghost" className="size-5 text-destructive hover:text-destructive" onClick={() => void deleteTask(task.id)} aria-label="Delete">
            <Trash2 className="size-2.5" />
          </Button>
        </div>
      </td>
    </tr>
  );
}

/* ── Draggable wrapper for dnd-kit ── */
function DraggableRow({ task, onEdit }: { task: Task; onEdit: (t: Task) => void }) {
  const { attributes, listeners, setNodeRef, isDragging } = useDraggable({ id: `task:${task.id}` });
  return (
    <div ref={setNodeRef} className={cn(isDragging && 'opacity-30')} {...attributes} {...listeners}>
      <table className="w-full"><tbody><TaskRow task={task} onEdit={onEdit} /></tbody></table>
    </div>
  );
}

/* ── Table header ── */
const TABLE_HEAD = (
  <thead>
    <tr className="border-b border-border text-[10px] text-muted-foreground uppercase tracking-wide">
      <th className="px-1.5 py-1 text-left w-6"></th>
      <th className="px-1.5 py-1 text-left">Task</th>
      <th className="px-1.5 py-1 text-left">Cat</th>
      <th className="px-1.5 py-1 text-left">Est</th>
      <th className="px-1.5 py-1 text-left">Eis</th>
      <th className="px-1.5 py-1 text-right w-24"></th>
    </tr>
  </thead>
);

/* ── Eisenhower quadrant as mini-table ── */
function QuadrantTable({ tasks, onEdit, category }: { tasks: Task[]; onEdit: (t: Task) => void; category: EisenhowerCategory }) {
  const meta = EISENHOWER_LABELS[category];
  return (
    <Card className="p-2">
      <div className="flex items-center justify-between mb-1 px-1">
        <span className="text-[11px] font-semibold">{meta.label}</span>
        <span className="text-[9px] text-muted-foreground tabular-nums">{tasks.length}</span>
      </div>
      {tasks.length === 0 ? (
        <p className="text-[10px] text-muted-foreground italic py-2 text-center">—</p>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-left"><tbody>
            {tasks.map((t) => (
              <TaskRow key={t.id} task={t} onEdit={onEdit} />
            ))}
          </tbody></table>
        </div>
      )}
    </Card>
  );
}

/* ── Eisenhower Matrix with axis labels ── */
function EisenhowerMatrix({ tasks, onEdit }: { tasks: Task[]; onEdit: (t: Task) => void }) {
  const grouped = useMemo(() => {
    const map: Record<EisenhowerCategory, Task[]> = { do_first: [], schedule: [], delegate: [], eliminate: [] };
    for (const t of tasks) map[t.eisenhowerCategory].push(t);
    return map;
  }, [tasks]);

  return (
    <div className="grid grid-cols-[auto_1fr_1fr] grid-rows-[auto_1fr_1fr] gap-1.5 items-start">
      {/* Column headers — Urgent / Not Urgent */}
      <div />
      <div className="text-[10px] font-semibold text-muted-foreground text-center pb-0.5">⚡ Urgent</div>
      <div className="text-[10px] font-semibold text-muted-foreground text-center pb-0.5">🌙 Not Urgent</div>

      {/* Row 1 — Important: Do First | Schedule */}
      <div className="flex items-center justify-center">
        <span className="text-[10px] font-semibold text-muted-foreground -rotate-90 whitespace-nowrap origin-center">★ Important</span>
      </div>
      <QuadrantTable tasks={grouped.do_first} onEdit={onEdit} category="do_first" />
      <QuadrantTable tasks={grouped.schedule} onEdit={onEdit} category="schedule" />

      {/* Row 2 — Not Important: Delegate | Eliminate */}
      <div className="flex items-center justify-center">
        <span className="text-[10px] font-semibold text-muted-foreground -rotate-90 whitespace-nowrap origin-center">☆ Less Impt.</span>
      </div>
      <QuadrantTable tasks={grouped.delegate} onEdit={onEdit} category="delegate" />
      <QuadrantTable tasks={grouped.eliminate} onEdit={onEdit} category="eliminate" />
    </div>
  );
}

/* ── Main component ── */
interface Props {
  variant: 'backlog' | 'incubator';
}

export function BacklogIncubator({ variant }: Props) {
  const allTasks = useAppStore((s) => s.tasks);
  const [view, setView] = useState<'matrix' | 'list'>(variant === 'backlog' ? 'matrix' : 'list');
  const [query, setQuery] = useState('');
  const [createOpen, setCreateOpen] = useState(false);
  const [editTask, setEditTask] = useState<Task | null>(null);

  const tasks = useMemo(() => allTasks.filter((t) => t.status === variant), [allTasks, variant]);
  const filtered = useMemo(() => tasks.filter((t) =>
    t.title.toLowerCase().includes(query.toLowerCase()) ||
    t.notes?.toLowerCase().includes(query.toLowerCase())
  ), [tasks, query]);

  const isBacklog = variant === 'backlog';
  const Icon = isBacklog ? Inbox : Lightbulb;
  const title = isBacklog ? 'Backlog' : 'Idea Incubator';

  return (
    <div className="space-y-2">
      {/* Toolbar */}
      <div className="flex items-center gap-2">
        <div className="flex items-center gap-1.5 text-muted-foreground">
          <Icon className="size-3.5" />
          <span className="text-xs font-semibold text-foreground">{title}</span>
          <span className="text-[10px] tabular-nums">({filtered.length})</span>
        </div>
        <div className="relative flex-1 max-w-xs">
          <Search className="absolute left-1.5 top-1/2 -translate-y-1/2 size-3 text-muted-foreground" />
          <Input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder={`Search…`}
            className="h-6 pl-6 text-[11px] bg-muted/50 border-border/50"
          />
        </div>
        {isBacklog && (
          <ToggleGroup type="single" value={view} onValueChange={(v) => v && setView(v as 'matrix' | 'list')} size="sm">
            <ToggleGroupItem value="matrix" aria-label="Matrix view" className="size-6"><Grid2x2 className="size-3" /></ToggleGroupItem>
            <ToggleGroupItem value="list" aria-label="List view" className="size-6"><ListIcon className="size-3" /></ToggleGroupItem>
          </ToggleGroup>
        )}
        <Button size="sm" variant="outline" className="h-6 text-[11px] px-2" onClick={() => { setEditTask(null); setCreateOpen(true); }}>
          <Plus className="size-3" /> Add
        </Button>
      </div>

      {/* Content */}
      {filtered.length === 0 ? (
        <div className="py-6 text-center text-xs text-muted-foreground">
          {query ? 'No matches' : 'Empty — add tasks above or capture via voice'}
        </div>
      ) : isBacklog && view === 'matrix' ? (
        <EisenhowerMatrix tasks={filtered} onEdit={(t) => { setEditTask(t); setCreateOpen(true); }} />
      ) : (
        <Card className="overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              {TABLE_HEAD}
              <tbody>
                {filtered.map((t) => (
                  <TaskRow key={t.id} task={t} onEdit={(t) => { setEditTask(t); setCreateOpen(true); }} />
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}

      <TaskFormDialog
        open={createOpen}
        onOpenChange={setCreateOpen}
        editTask={editTask}
        defaultStatus={variant}
      />
    </div>
  );
}

// components/orchestrator/BacklogIncubator.vue
<template>
  <div class="space-y-2">
    <!-- Toolbar -->
    <div class="flex flex-wrap items-center gap-1.5 sm:gap-2">
      <div class="flex items-center gap-1.5 text-muted-foreground">
        <component :is="isBacklog ? Inbox : Lightbulb" class="size-3.5 sm:size-4" />
        <span class="text-xs sm:text-sm font-semibold text-foreground">{{ title }}</span>
        <span class="text-[10px] tabular-nums">({{ filtered.length }})</span>
      </div>
      <div class="relative flex-1 min-w-[100px] sm:min-w-[120px] max-w-xs">
        <Search class="absolute left-1.5 top-1/2 -translate-y-1/2 size-3 text-muted-foreground" />
        <Input v-model="query" placeholder="Search…" class="h-7 sm:h-6 pl-6 text-[11px] bg-muted/50 border-border/50" />
      </div>
      <div v-if="isBacklog" class="inline-flex rounded-md border border-border/50 overflow-hidden">
        <button :class="cn('size-7 sm:size-6 flex items-center justify-center', view === 'matrix' ? 'bg-muted' : 'hover:bg-muted/50')" aria-label="Matrix view" @click="view = 'matrix'"><Grid2x2 class="size-3" /></button>
        <button :class="cn('size-7 sm:size-6 flex items-center justify-center', view === 'list' ? 'bg-muted' : 'hover:bg-muted/50')" aria-label="List view" @click="view = 'list'"><ListIcon class="size-3" /></button>
      </div>
      <Button size="sm" variant="outline" class="h-7 sm:h-6 text-[11px] px-2 gap-1" @click="importOpen = true">
        <FileText class="size-3" /> <span class="hidden xs:inline">Import</span>
      </Button>
      <Button size="sm" variant="outline" class="h-7 sm:h-6 text-[11px] px-2 gap-1" @click="openCreate()">
        <Plus class="size-3" /> Add
      </Button>
    </div>

    <!-- Content -->
    <div v-if="filtered.length === 0" class="py-6 sm:py-8 text-center text-xs text-muted-foreground">
      {{ query ? 'No matches' : 'Empty — add tasks above or capture via voice' }}
    </div>

    <!-- Eisenhower matrix -->
    <div v-else-if="isBacklog && view === 'matrix'">
      <div class="grid grid-cols-1 gap-1.5 md:hidden">
        <QuadrantCard v-for="q in quadrantsMobile" :key="q.cat" :label="q.label" :cat="q.cat" :tasks="grouped[q.cat]"
          :hovered="hoveredCat === q.cat" @drop-task="onQuadrantDrop" @dragover-cat="hoveredCat = $event"
          @edit="openEdit" @drag-start="onTaskDragStart" @drag-end="onDragEnd" />
      </div>
      <div class="hidden md:grid grid-cols-[auto_1fr_1fr] grid-rows-[auto_1fr_1fr] gap-1.5 lg:gap-2 items-start">
        <div />
        <div class="text-[10px] font-semibold text-muted-foreground text-center pb-0.5">⚡ Urgent</div>
        <div class="text-[10px] font-semibold text-muted-foreground text-center pb-0.5">🌙 Not Urgent</div>
        <div class="flex items-center justify-center"><span class="text-[10px] font-semibold text-muted-foreground -rotate-90 whitespace-nowrap">★ Important</span></div>
        <QuadrantCard cat="do_first" :tasks="grouped.do_first" :hovered="hoveredCat === 'do_first'" @drop-task="onQuadrantDrop" @dragover-cat="hoveredCat = $event" @edit="openEdit" @drag-start="onTaskDragStart" @drag-end="onDragEnd" />
        <QuadrantCard cat="schedule" :tasks="grouped.schedule" :hovered="hoveredCat === 'schedule'" @drop-task="onQuadrantDrop" @dragover-cat="hoveredCat = $event" @edit="openEdit" @drag-start="onTaskDragStart" @drag-end="onDragEnd" />
        <div class="flex items-center justify-center"><span class="text-[10px] font-semibold text-muted-foreground -rotate-90 whitespace-nowrap">☆ Less Impt.</span></div>
        <QuadrantCard cat="delegate" :tasks="grouped.delegate" :hovered="hoveredCat === 'delegate'" @drop-task="onQuadrantDrop" @dragover-cat="hoveredCat = $event" @edit="openEdit" @drag-start="onTaskDragStart" @drag-end="onDragEnd" />
        <QuadrantCard cat="eliminate" :tasks="grouped.eliminate" :hovered="hoveredCat === 'eliminate'" @drop-task="onQuadrantDrop" @dragover-cat="hoveredCat = $event" @edit="openEdit" @drag-start="onTaskDragStart" @drag-end="onDragEnd" />
      </div>
    </div>

    <!-- List view (reorderable) -->
    <Card v-else class="overflow-hidden">
      <div class="overflow-x-auto">
        <table class="w-full text-left">
          <thead>
            <tr class="border-b border-border text-[10px] text-muted-foreground uppercase tracking-wide">
              <th class="px-1.5 py-0.5 w-6"></th>
              <th class="px-1.5 py-0.5">Task</th>
              <th class="px-1.5 py-0.5 hidden xs:table-cell">Cat</th>
              <th class="px-1.5 py-0.5 hidden sm:table-cell">Est</th>
              <th class="px-1.5 py-0.5 text-right w-20"></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(t, idx) in liveList" :key="t.id" draggable="true"
              :class="cn('group border-b border-border/50 last:border-0 hover:bg-muted/30 transition-colors cursor-grab active:cursor-grabbing', dragIndex === idx && 'opacity-40')"
              @dragstart="onListDragStart(idx)" @dragover.prevent="onListDragOver(idx)" @dragend="onListDragEnd">
              <td class="px-1.5 py-1 w-6"><GripVertical class="size-3 text-muted-foreground/50" /></td>
              <td class="px-1.5 py-1 min-w-0">
                <div class="flex items-center gap-1.5">
                  <Checkbox :checked="t.status === 'completed'" :aria-label="`Complete ${t.title}`" @change="(v) => v ? store.completeTask(t.id) : store.uncompleteTask(t.id)" />
                  <span :class="cn('block text-xs font-medium truncate max-w-[150px] xs:max-w-[220px] sm:max-w-[320px] md:max-w-[480px]', t.status === 'completed' && 'line-through text-muted-foreground')">{{ t.title }}</span>
                </div>
              </td>
              <td class="px-1.5 py-1 text-[10px] whitespace-nowrap hidden xs:table-cell">
                <span :class="cn('inline-block rounded px-1 py-px font-medium', catColor(t.category))">{{ t.category }}</span>
              </td>
              <td class="px-1.5 py-1 text-[10px] text-muted-foreground tabular-nums whitespace-nowrap hidden sm:table-cell">{{ formatDuration(t.estimatedMinutes) }}</td>
              <td class="px-1.5 py-1">
                <div class="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity">
                  <Button v-if="t.status !== 'completed'" size="icon" variant="ghost" class="size-6" aria-label="Do today" title="Do today" @click="store.updateTask(t.id, { status: 'today' })"><CalendarClock class="size-3" /></Button>
                  <Button size="icon" variant="ghost" class="size-6" aria-label="Edit" @click="openEdit(t)"><Pencil class="size-3" /></Button>
                  <Button size="icon" variant="ghost" class="size-6 text-destructive hover:text-destructive" aria-label="Delete" @click="store.deleteTask(t.id)"><Trash2 class="size-3" /></Button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Card>

    <TaskFormDialog :open="createOpen" :edit-task="editTask" :default-status="variant" @update:open="createOpen = $event" />
    <NotesImporter :open="importOpen" :default-status="variant" @update:open="importOpen = $event" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { Inbox, Lightbulb, Plus, Search, Grid2x2, List as ListIcon, Pencil, Trash2, CalendarClock, GripVertical, FileText } from 'lucide-vue-next';
import { useAppStore } from '~/stores/app';
import { useToast } from '~/composables/useToast';
import { cn } from '~/lib/utils';
import { CATEGORY_COLORS, EISENHOWER_LABELS, type Task, type EisenhowerCategory } from '~/lib/types';
import { formatDuration } from '~/lib/time-utils';
import QuadrantCard from './QuadrantCard.vue';

const props = defineProps<{ variant: 'backlog' | 'incubator' }>();
const store = useAppStore();
const { toast } = useToast();

const view = ref<'matrix' | 'list'>(props.variant === 'backlog' ? 'matrix' : 'list');
const query = ref('');
const createOpen = ref(false);
const importOpen = ref(false);
const editTask = ref<Task | null>(null);

const isBacklog = computed(() => props.variant === 'backlog');
const title = computed(() => (isBacklog.value ? 'Backlog' : 'Idea Incubator'));
const catColor = (c: string) => CATEGORY_COLORS[c] ?? CATEGORY_COLORS.Admin;

const tasks = computed(() => store.tasks.filter((t) => t.status === props.variant));
const filtered = computed(() => tasks.value.filter((t) =>
  t.title.toLowerCase().includes(query.value.toLowerCase()) || t.notes?.toLowerCase().includes(query.value.toLowerCase())));

const grouped = computed(() => {
  const map: Record<EisenhowerCategory, Task[]> = { do_first: [], schedule: [], delegate: [], eliminate: [] };
  for (const t of filtered.value) map[t.eisenhowerCategory].push(t);
  return map;
});

const quadrantsMobile = [
  { cat: 'do_first' as EisenhowerCategory, label: 'Do First ⚡★' },
  { cat: 'schedule' as EisenhowerCategory, label: 'Schedule 🌙★' },
  { cat: 'delegate' as EisenhowerCategory, label: 'Delegate ⚡☆' },
  { cat: 'eliminate' as EisenhowerCategory, label: 'Eliminate 🌙☆' },
];

// Matrix drag
const draggingTaskId = ref<string | null>(null);
const hoveredCat = ref<EisenhowerCategory | null>(null);
function onTaskDragStart(id: string) { draggingTaskId.value = id; }
function onDragEnd() { draggingTaskId.value = null; hoveredCat.value = null; }
async function onQuadrantDrop(cat: EisenhowerCategory) {
  const id = draggingTaskId.value;
  hoveredCat.value = null;
  draggingTaskId.value = null;
  if (!id) return;
  const task = store.tasks.find((t) => t.id === id);
  if (!task || task.eisenhowerCategory === cat) return;
  await store.updateTask(id, { eisenhowerCategory: cat });
  toast({ title: 'Moved', description: `${task.title} → ${EISENHOWER_LABELS[cat].label}` });
}

// List reorder
const liveList = ref<Task[]>([]);
watch(filtered, (v) => { liveList.value = [...v]; }, { immediate: true });
const dragIndex = ref<number | null>(null);
function onListDragStart(idx: number) { dragIndex.value = idx; }
function onListDragOver(idx: number) {
  if (dragIndex.value === null || dragIndex.value === idx) return;
  const arr = [...liveList.value];
  const [moved] = arr.splice(dragIndex.value, 1);
  arr.splice(idx, 0, moved);
  liveList.value = arr;
  dragIndex.value = idx;
}
function onListDragEnd() {
  dragIndex.value = null;
  store.reorderTasks(liveList.value.map((t) => t.id));
}

function openCreate() { editTask.value = null; createOpen.value = true; }
function openEdit(t: Task) { editTask.value = t; createOpen.value = true; }
</script>
